### ISSUE TITLE
Troubleshooting or error logging help?

### ISSUE THREAD

**Issue by Roucou** [philpagel/debian-headless#16]
I cannot get this working, i.e. after running `qemu-bios` or `qemu-uefi` the VM boots and briefly shows "Booting Install" before switching to a blank screen with a single underscore character in the top-left corner. If I launch `ssh installer@localhost -p22222` it  times out. Using `telnet localhost 33333` also doesn't show anything.

What options do I have to troubleshoot this?

This is the initial part of my `Makevars` file:

```
SOURCE = debian-12.0.0-amd64-netinst.iso
TARGET = debian-12.0.0-amd64-netinst-hl.iso
LABEL = Debian-12.0.0-amd64-headless
ARCH = amd64
USBDEV = /dev/sda

```
Everything below that is left as-is.

And this is my `preseed.cfg` file:

```
#_preseed_V1
d-i debconf/language string en
d-i debian-installer/country string US
d-i debian-installer/language string en
d-i debian-installer/locale select en_US.UTF-8
d-i keyboard-configuration/layoutcode string us
d-i keyboard-configuration/xkb-keymap select us
d-i netcfg/choose_interface select auto
d-i netcfg/disable_autoconfig boolean true
d-i netcfg/get_domain string somenetwork.lan
d-i netcfg/get_gateway string 192.168.1.250
d-i netcfg/get_hostname string nas
d-i netcfg/get_ipaddress string 192.168.1.203
d-i netcfg/get_nameservers string 192.168.1.250
d-i netcfg/get_netmask string 255.255.255.0
d-i netcfg/hostname string nas
d-i netcfg/confirm_static boolean true
d-i anna/choose_modules string network-console
d-i network-console/start select continue
d-i network-console/password password r00tme
d-i network-console/password-again password r00tme

```

I verified this preseed.cfg indeed ends up in `initrd.gz`, which it does.

Any help would be greatly appreciated! :-)

**Comment by philpagel** [comment]
Strange – it is indeed broken! I'm pretty puzzled because I successfully used it not long ago and it certainly was working when I made my last commit. I'll have to investigate a bit...

**Comment by philpagel** [comment]
OK – I think I found it. I had accidentally commited a change of the serial console device to `/dev/ttyS1` which will not work in qemu and probably also on many physical machines. I reverted that to `/dev/ttyS0` and now it works again. Please let me know if you still have any issues or if it does now also work for you.

It is normal that you will only see a blinking cursor in the qemu window, because the console is redirected to the serial console, by default. But telnet should be working immediately and ssh after the network setup is complete (That can take quite a while...).
If you want to change that behavior, you can do so by setting  `CONSOLE` to a different value further down in the config file.

**Comment by Roucou** [comment]
Fantastic, that indeed resolved the issue, many thanks!

**Comment by philpagel** [comment]
Excellent. Closing the issue as resolved.
